language: csharp
solution: ConsoleApp1.sln
dotnet: 3.1
mono: none
 
script:
 - dotnet restore #this will restore are settings and get all our NuGet packages
 - dotnet test #this will run all our tests